---
- name: Install strongswan packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - charon-systemd

- name: Configure strongswan.conf
  ansible.builtin.template:
    src: strongswan.conf.j2
    dest: "{{ strongswan_conf_file }}"
    owner: root
    group: root
    mode: 0644
  when: strongswan_settings is defined
  notify:
    - Restart strongswan

- name: Configure swanctl.conf
  ansible.builtin.template:
    src: swanctl.conf.j2
    dest: "{{ strongswan_swanctl_config_file }}"
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart strongswan
  when: strongswan_swanctl_settings is defined

- name: Ensure Strongswan service is enabled and started
  ansible.builtin.systemd:
    name: "{{ strongswan_swanctl_svc }}"
    state: started
    enabled: true
    daemon_reload: true
