---
- name: Converge
  hosts: all
  become: true

  pre_tasks:
    - name: Update apt cache.
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_facts['os_family'] == "Debian"

  tasks:
    - name: "Include poppen.strongswan"
      ansible.builtin.include_role:
        name: "poppen.strongswan"
